- name: Deploy Java Application to Docker
  hosts: app
  become: true

  tasks:
    - name: Pull latest image from Docker Hub
      community.docker.docker_image:
        name: prawin03sm/devops-webapp
        tag: latest
        source: pull
        
    - name: Stop and remove old container if running
      community.docker.docker_container:
        name: devops-webapp
        state: absent

    - name: Run new application container
      community.docker.docker_container:
        name: devops-webapp
        image: prawin03sm/devops-webapp:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
