- name: Deploy Java Application to Docker
  hosts: app
  become: true

  tasks:
    - name: Stop and remove old container if running
      community.docker.docker_container:
        name: devops-webapp
        state: absent

    - name: Run new application container
      community.docker.docker_container:
        name: devops-webapp
        image: devops-webapp:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
